import type { DemoUniversityProgram } from "./types";

/**
 * Fictional universities and programs used only to exercise the Match Quiz
 * UI and scoring engine end to end. None of these are real institutions --
 * app/[locale]/explore/match/results/page.tsx surfaces them behind an
 * explicit "DEMO DATA" badge. UniPath's real university/program catalog
 * (public.universities / public.programs) doesn't yet carry the
 * tuition/ranking/campus-life attributes the match engine needs, and this
 * project's policy is to never invent official figures for real schools --
 * so this stand-in dataset exists to let the feature be demoed honestly
 * until that catalog is populated.
 */
export const DEMO_CATALOG: DemoUniversityProgram[] = [
  {
    id: "demo-northbridge-cs",
    universityName: "Northbridge Institute of Technology",
    countryCode: "US",
    city: "Ashford Falls",
    environment: "urban",
    climate: "cold",
    studentBodySize: "large",
    programName: "BSc Computer Science",
    degreeType: "bachelor",
    field: "Computer Science",
    language: "English",
    tuitionAmount: 48000,
    tuitionCurrency: "USD",
    livingCostAmount: 24000,
    livingCostCurrency: "USD",
    academicQualityScore: 5,
    rankingScore: 5,
    employmentScore: 5,
    safetyScore: 4,
    internationalCommunityScore: 4,
    researchScore: 5,
    campusLifeScore: 4,
    workWhileStudyingScore: 4,
    scholarshipsAvailable: true,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-lindenhoven-ds",
    universityName: "Lindenhoven University of Applied Sciences",
    countryCode: "DE",
    city: "Lindenhoven",
    environment: "suburban",
    climate: "moderate",
    studentBodySize: "medium",
    programName: "MSc Data Science",
    degreeType: "master",
    field: "Data Science",
    language: "English",
    tuitionAmount: 3500,
    tuitionCurrency: "EUR",
    livingCostAmount: 12000,
    livingCostCurrency: "EUR",
    academicQualityScore: 4,
    rankingScore: 3,
    employmentScore: 4,
    safetyScore: 5,
    internationalCommunityScore: 4,
    researchScore: 4,
    campusLifeScore: 3,
    workWhileStudyingScore: 4,
    scholarshipsAvailable: true,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-ashcombe-arch",
    universityName: "Ashcombe College of Design",
    countryCode: "GB",
    city: "Ashcombe",
    environment: "urban",
    climate: "moderate",
    studentBodySize: "small",
    programName: "BA Architecture",
    degreeType: "bachelor",
    field: "Architecture",
    language: "English",
    tuitionAmount: 26000,
    tuitionCurrency: "GBP",
    livingCostAmount: 15000,
    livingCostCurrency: "GBP",
    academicQualityScore: 4,
    rankingScore: 4,
    employmentScore: 3,
    safetyScore: 4,
    internationalCommunityScore: 5,
    researchScore: 3,
    campusLifeScore: 5,
    workWhileStudyingScore: 3,
    scholarshipsAvailable: false,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-zuiderpark-me",
    universityName: "Zuiderpark Institute of Technology",
    countryCode: "NL",
    city: "Zuiderpark",
    environment: "suburban",
    climate: "moderate",
    studentBodySize: "medium",
    programName: "MSc Mechanical Engineering",
    degreeType: "master",
    field: "Mechanical Engineering",
    language: "English",
    tuitionAmount: 15000,
    tuitionCurrency: "EUR",
    livingCostAmount: 13000,
    livingCostCurrency: "EUR",
    academicQualityScore: 4,
    rankingScore: 4,
    employmentScore: 4,
    safetyScore: 5,
    internationalCommunityScore: 5,
    researchScore: 4,
    campusLifeScore: 4,
    workWhileStudyingScore: 4,
    scholarshipsAvailable: true,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-kitayama-ba",
    universityName: "Kitayama University",
    countryCode: "JP",
    city: "Kitayama",
    environment: "urban",
    climate: "moderate",
    studentBodySize: "large",
    programName: "BA Business Administration",
    degreeType: "bachelor",
    field: "Business Administration",
    language: "English / Japanese",
    tuitionAmount: 900000,
    tuitionCurrency: "JPY",
    livingCostAmount: 1100000,
    livingCostCurrency: "JPY",
    academicQualityScore: 3,
    rankingScore: 3,
    employmentScore: 3,
    safetyScore: 5,
    internationalCommunityScore: 3,
    researchScore: 2,
    campusLifeScore: 3,
    workWhileStudyingScore: 3,
    scholarshipsAvailable: false,
    minIeltsScore: 6,
  },
  {
    id: "demo-bellhaven-env",
    universityName: "Bellhaven University",
    countryCode: "AU",
    city: "Bellhaven",
    environment: "suburban",
    climate: "warm",
    studentBodySize: "medium",
    programName: "MSc Environmental Science",
    degreeType: "master",
    field: "Environmental Science",
    language: "English",
    tuitionAmount: 32000,
    tuitionCurrency: "AUD",
    livingCostAmount: 20000,
    livingCostCurrency: "AUD",
    academicQualityScore: 4,
    rankingScore: 4,
    employmentScore: 3,
    safetyScore: 5,
    internationalCommunityScore: 5,
    researchScore: 4,
    campusLifeScore: 4,
    workWhileStudyingScore: 3,
    scholarshipsAvailable: true,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-portview-cs",
    universityName: "Portview Institute of Technology",
    countryCode: "SG",
    city: "Portview",
    environment: "urban",
    climate: "warm",
    studentBodySize: "medium",
    programName: "BEng Computer Science",
    degreeType: "bachelor",
    field: "Computer Science",
    language: "English",
    tuitionAmount: 28000,
    tuitionCurrency: "SGD",
    livingCostAmount: 16000,
    livingCostCurrency: "SGD",
    academicQualityScore: 5,
    rankingScore: 4,
    employmentScore: 5,
    safetyScore: 5,
    internationalCommunityScore: 5,
    researchScore: 4,
    campusLifeScore: 3,
    workWhileStudyingScore: 4,
    scholarshipsAvailable: false,
    minIeltsScore: 6,
  },
  {
    id: "demo-northgate-psych",
    universityName: "Northgate University",
    countryCode: "CA",
    city: "Northgate",
    environment: "suburban",
    climate: "cold",
    studentBodySize: "large",
    programName: "BA Psychology",
    degreeType: "bachelor",
    field: "Psychology",
    language: "English",
    tuitionAmount: 24000,
    tuitionCurrency: "CAD",
    livingCostAmount: 15000,
    livingCostCurrency: "CAD",
    academicQualityScore: 3,
    rankingScore: 3,
    employmentScore: 3,
    safetyScore: 5,
    internationalCommunityScore: 4,
    researchScore: 2,
    campusLifeScore: 4,
    workWhileStudyingScore: 3,
    scholarshipsAvailable: true,
    minIeltsScore: 6.5,
  },
  {
    id: "demo-montefiore-econ",
    universityName: "Montefiore University",
    countryCode: "IT",
    city: "Montefiore",
    environment: "rural",
    climate: "moderate",
    studentBodySize: "small",
    programName: "MSc Economics",
    degreeType: "master",
    field: "Economics",
    language: "English / Italian",
    tuitionAmount: 4000,
    tuitionCurrency: "EUR",
    livingCostAmount: 9000,
    livingCostCurrency: "EUR",
    academicQualityScore: 3,
    rankingScore: 2,
    employmentScore: 3,
    safetyScore: 4,
    internationalCommunityScore: 3,
    researchScore: 3,
    campusLifeScore: 4,
    workWhileStudyingScore: 2,
    scholarshipsAvailable: true,
    minIeltsScore: 6,
  },
  {
    id: "demo-verdenoix-ba",
    universityName: "Verdenoix Grande École",
    countryCode: "FR",
    city: "Verdenoix",
    environment: "urban",
    climate: "moderate",
    studentBodySize: "medium",
    programName: "MSc Business Administration",
    degreeType: "master",
    field: "Business Administration",
    language: "English / French",
    tuitionAmount: 18000,
    tuitionCurrency: "EUR",
    livingCostAmount: 14000,
    livingCostCurrency: "EUR",
    academicQualityScore: 4,
    rankingScore: 4,
    employmentScore: 4,
    safetyScore: 4,
    internationalCommunityScore: 4,
    researchScore: 3,
    campusLifeScore: 4,
    workWhileStudyingScore: 3,
    scholarshipsAvailable: false,
    minIeltsScore: 6.5,
  },
];
